// Mock data for VK Digital ISP website

export const brand = {
  name: "VK DIGITAL",
  tagline: "High Speed Internet Services",
  logo: "https://customer-assets.emergentagent.com/job_plant-based-hub-4/artifacts/50iizffb_Screenshot_20260423_010217_Canva.jpg",
  email: "vkdigitaltiptur@gmail.com",
  phone: "+919148287555",
  phoneDisplay: "+91 91482 87555",
  ownerPhone: "+917259326656",
  ownerPhoneDisplay: "+91 72593 26656",
  helpdeskPhone: "+919148287555",
  helpdeskPhoneDisplay: "+91 91482 87555",
  address: "VK DIGITAL, Near: Vijaya Nursing Home, BH Road, Tiptur 572201",
  about: "We believe it has the power to do amazing things.",
  copyright: "\u00a9 2024-2025 VK Digital. All Rights Reserved.",
};

export const navLinks = [
  { label: "Home", to: "/" },
  { label: "About Us", to: "/about" },
  { label: "Home Plans", to: "/home-plans" },
  { label: "Business Plans", to: "/business-plans" },
  { label: "OTT", to: "/ott" },
  { label: "IPTV", to: "/iptv" },
  { label: "Contact Us", to: "/contact" },
];

export const heroSlides = [
  {
    id: 1,
    title: "Connect with the Most Reliable Broadband",
    titleKn: "ಅತ್ಯಂತ ವಿಶ್ವಾಸಾರ್ಹ ಬ್ರಾಡ್‌ಬ್ಯಾಂಡ್‌ಗೆ ಸಂಪರ್ಕಿಸಿ",
    subtitle: "Explore Our Exclusive OTT Internet Combo Plan",
    subtitleKn: "ನಮ್ಮ ವಿಶೇಷ OTT ಇಂಟರ್ನೆಟ್ ಕಾಂಬೊ ಪ್ಲಾನ್ ಅನ್ವೇಷಿಸಿ",
    highlight: "Entertainment & Connectivity",
    highlightKn: "ಮನೋರಂಜನೆ ಮತ್ತು ಸಂಪರ್ಕ",
    price: "50 Mbps @ \u20b9499/-",
    extra: "350+ LIVE TV CHANNELS",
    extraKn: "350+ ಲೈವ್ ಟಿವಿ ಚಾನೆಲ್‌ಗಳು",
    image: "https://images.unsplash.com/photo-1692188071339-2825a8a997f1?w=1600&q=80",
  },
  {
    id: 2,
    title: "Blazing Fast Fiber Internet",
    titleKn: "ಅತ್ಯಂತ ವೇಗದ ಫೈಬರ್ ಇಂಟರ್ನೆಟ್",
    subtitle: "Stream. Work. Play. Without Limits.",
    subtitleKn: "ಸ್ಟ್ರೀಮ್. ಕೆಲಸ. ಆಟ. ಮಿತಿಯಿಲ್ಲದೆ.",
    highlight: "Unlimited Data, Zero Buffering",
    highlightKn: "ಅಮಿತ ಡೇಟಾ, ಶೂನ್ಯ ಬಫರಿಂಗ್",
    price: "100 Mbps @ \u20b9699/-",
    extra: "20+ OTT APPS INCLUDED",
    extraKn: "20+ OTT ಅಪ್ಲಿಕೇಶನ್‌ಗಳು ಸೇರಿವೆ",
    image: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=1600&q=80",
  },
  {
    id: 3,
    title: "Upgrade Your Home Network",
    titleKn: "ನಿಮ್ಮ ಮನೆಯ ನೆಟ್‌ವರ್ಕ್ ಅನ್ನು ಮೇಲ್ದರ್ಜೆಗೇರಿಸಿ",
    subtitle: "Free Installation. Free WiFi Router.",
    subtitleKn: "ಉಚಿತ ಅಳವಡಿಕೆ. ಉಚಿತ ವೈಫೈ ರೂಟರ್.",
    highlight: "Experience The Difference",
    highlightKn: "ವ್ಯತ್ಯಾಸವನ್ನು ಅನುಭವಿಸಿ",
    price: "Starts @ \u20b9399/-",
    extra: "UNLIMITED BROWSING",
    extraKn: "ಅಮಿತ ಬ್ರೌಸಿಂಗ್",
    image: "https://images.pexels.com/photos/29711663/pexels-photo-29711663.jpeg?w=1600&q=80",
  },
  {
    id: 4,
    title: "All In One Plan",
    titleKn: "ಆಲ್ ಇನ್ ಒನ್ ಪ್ಲಾನ್",
    subtitle: "Best Plan for Home and Entertainment",
    subtitleKn: "ಮನೆ ಮತ್ತು ಮನೋರಂಜನೆಗೆ ಅತ್ಯುತ್ತಮ ಪ್ಲಾನ್",
    highlight: "Experience The Difference",
    highlightKn: "ವ್ಯತ್ಯಾಸವನ್ನು ಅನುಭವಿಸಿ",
    price: "Starts @ \u20b9599/-",
    extra: "SPEED + 350 LIVE TV CHANNELS + 10 OTTs",
    extraKn: "ವೇಗ + 350 ಲೈವ್ ಟಿವಿ ಚಾನೆಲ್‌ಗಳು + 10 OTTs",
    image: "https://images.unsplash.com/photo-1601944179066-29786cb9d32a?w=1600&q=80",
  },
  {
    id: 5,
    title: "As Per Your Need",
    titleKn: "ನಿಮ್ಮ ಅಗತ್ಯಕ್ಕೆ ತಕ್ಕಂತೆ",
    subtitle: "Customisable Plan",
    subtitleKn: "ಕಸ್ಟಮೈಸ್ ಮಾಡಬಹುದಾದ ಪ್ಲಾನ್",
    highlight: "Most Reliable Internet and Best Entertainment",
    highlightKn: "ಅತ್ಯಂತ ವಿಶ್ವಾಸಾರ್ಹ ಇಂಟರ್ನೆಟ್ ಮತ್ತು ಅತ್ಯುತ್ತಮ ಮನೋರಂಜನೆ",
    price: "Starts @ \u20b9199/-",
    extra: "BEST FOR BILLING & CCTV FOR SHOPS",
    extraKn: "ಅಂಗಡಿಗಳ ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು ಸಿಸಿಟಿವಿಗೆ ಉತ್ತಮ",
    image: "https://images.pexels.com/photos/32698507/pexels-photo-32698507.jpeg?w=1600&q=80",
  },
];

// Section titles / labels in Kannada for bilingual display
export const i18n = {
  quickPay: { en: "Quick Pay", kn: "ತ್ವರಿತ ಪಾವತಿ" },
  myAccount: { en: "My Account", kn: "ನನ್ನ ಖಾತೆ" },
  viewPlans: { en: "View Plans", kn: "ಪ್ಲಾನ್‌ಗಳನ್ನು ನೋಡಿ" },
  checkAvailability: { en: "Check Availability", kn: "ಲಭ್ಯತೆ ಪರಿಶೀಲಿಸಿ" },
  bestNetwork: { en: "Best Network", kn: "ಉತ್ತಮ ನೆಟ್‌ವರ್ಕ್" },
  findPlans: {
    en: "Find Perfect Network Solutions",
    kn: "ಪರಿಪೂರ್ಣ ನೆಟ್‌ವರ್ಕ್ ಪರಿಹಾರಗಳನ್ನು ಹುಡುಕಿ",
  },
  startsFrom: { en: "Starts From", kn: "ಪ್ರಾರಂಭ" },
  popular: { en: "Popular", kn: "ಜನಪ್ರಿಯ" },
  subscribeNow: { en: "Subscribe Now", kn: "ಈಗ ಚಂದಾದಾರರಾಗಿ" },
  enjoyMore: {
    en: "Enjoy Sports, Movies, TV Shows & More.",
    kn: "ಕ್ರೀಡೆ, ಚಲನಚಿತ್ರ, ಟಿವಿ ಶೋಗಳನ್ನು ಆನಂದಿಸಿ.",
  },
  needFast: {
    en: "Need Fast & Secure Internet!",
    kn: "ವೇಗದ ಮತ್ತು ಸುರಕ್ಷಿತ ಇಂಟರ್ನೆಟ್ ಬೇಕೇ!",
  },
  useVk: { en: "Use VK Digital", kn: "VK ಡಿಜಿಟಲ್ ಬಳಸಿ" },
  viewAllPlans: { en: "View All Plans", kn: "ಎಲ್ಲಾ ಪ್ಲಾನ್‌ಗಳು" },
  ottHeading: {
    en: "Popular OTT Services We Offer",
    kn: "ನಾವು ನೀಡುವ ಜನಪ್ರಿಯ OTT ಸೇವೆಗಳು",
  },
  stats: {
    ultraSpeed: { en: "Ultra Fast Speed", kn: "ಅತಿ ವೇಗದ ಸ್ಪೀಡ್" },
    customerSupport: { en: "Customer Support", kn: "ಗ್ರಾಹಕ ಬೆಂಬಲ" },
    liveChannels: { en: "Live TV Channels", kn: "ಲೈವ್ ಟಿವಿ ಚಾನೆಲ್‌ಗಳು" },
    ottApps: { en: "OTT Applications", kn: "OTT ಅಪ್ಲಿಕೇಶನ್‌ಗಳು" },
  },
  features: {
    upTo: { en: "Up to", kn: "ವರೆಗೆ" },
    unlimitedData: { en: "Unlimited Data", kn: "ಅಮಿತ ಡೇಟಾ" },
    freeInstall: { en: "Free Installation", kn: "ಉಚಿತ ಅಳವಡಿಕೆ" },
    freeRouter: { en: "Free WiFi router*", kn: "ಉಚಿತ ವೈಫೈ ರೂಟರ್*" },
    liveTv: { en: "350 Live Channels", kn: "350 ಲೈವ್ ಚಾನೆಲ್‌ಗಳು" },
    ottApps: { en: "22 OTT", kn: "22 OTT ಅಪ್ಲಿಕೇಶನ್‌ಗಳು" },
  },
  footer: {
    quickLinks: { en: "Quick Links", kn: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು" },
    address: { en: "Address:", kn: "ವಿಳಾಸ:" },
    helpdesk: { en: "24/7 Helpdesk", kn: "24/7 ಸಹಾಯವಾಣಿ" },
    owner: { en: "Owner", kn: "ಮಾಲೀಕರು" },
    interested: { en: "Interested in working with us?", kn: "ನಮ್ಮೊಂದಿಗೆ ಕೆಲಸ ಮಾಡಲು ಆಸಕ್ತಿಯಿದೆಯೇ?" },
  },
  contact: {
    getInTouch: { en: "Get In Touch", kn: "ಸಂಪರ್ಕದಲ್ಲಿರಿ" },
    checkArea: {
      en: "Check Availability in Your Area",
      kn: "ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಲಭ್ಯತೆ ಪರಿಶೀಲಿಸಿ",
    },
    ourOffice: { en: "Our Office", kn: "ನಮ್ಮ ಕಚೇರಿ" },
    callUs: { en: "Call Us", kn: "ನಮಗೆ ಕರೆ ಮಾಡಿ" },
    emailUs: { en: "Email Us", kn: "ಇಮೇಲ್ ಮಾಡಿ" },
    supportHours: { en: "Support Hours", kn: "ಬೆಂಬಲದ ಸಮಯ" },
    enquireNow: { en: "Enquire Now", kn: "ಈಗ ವಿಚಾರಿಸಿ" },
    fullName: { en: "Full Name", kn: "ಪೂರ್ಣ ಹೆಸರು" },
    phone: { en: "Phone Number", kn: "ಫೋನ್ ಸಂಖ್ಯೆ" },
    email: { en: "Email Address", kn: "ಇಮೇಲ್ ವಿಳಾಸ" },
    addressField: { en: "Your Address / Locality", kn: "ನಿಮ್ಮ ವಿಳಾಸ / ಪ್ರದೇಶ" },
    message: { en: "How can we help you?", kn: "ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?" },
    submit: { en: "Submit Enquiry", kn: "ವಿಚಾರಣೆ ಸಲ್ಲಿಸಿ" },
  },
};

export const plans = [
  {
    id: "internet",
    title: "Internet",
    popular: false,
    icon: "Wifi",
    features: [
      "Up to 50Mbps",
      "Free Installation",
      "Free WiFi router*",
    ],
    price: "\u20b9399",
    note: "Starts From",
    cycle: "/ Month",
    cta: "View Plans",
    link: "/home-plans",
  },
  {
    id: "internet-ott",
    title: "Internet + OTT",
    popular: false,
    icon: "MonitorPlay",
    features: [
      "Up to 50Mbps",
      "22 OTT",
      "Free Installation",
      "Free WiFi router*",
    ],
    price: "\u20b9599",
    note: "Starts From",
    cycle: "/ Month",
    cta: "View Plans",
    link: "/home-plans",
  },
  {
    id: "internet-ott-iptv",
    title: "Internet + OTT + IPTV",
    popular: true,
    icon: "Tv",
    features: [
      "Up to 50Mbps",
      "22 OTT",
      "350 Live Channels",
      "Free Installation",
      "Free WiFi router*",
    ],
    price: "\u20b9699",
    note: "Starts From",
    cycle: "/ Month",
    cta: "View Plans",
    link: "/home-plans",
  },
  {
    id: "business",
    title: "Internet + OTT + IPTV",
    popular: true,
    icon: "Tv",
    features: [
      "Up to 100Mbps",
      "22 OTT",
      "350 Live Channels",
      "Free Installation",
      "Free WiFi router*",
    ],
    price: "\u20b9899",
    note: "Starts From",
    cycle: "/ Month",
    cta: "View Plans",
    link: "/home-plans",
  },
];

export const homePlans = [
  { id: 1, speed: "50 Mbps", price: 399, validity: "1 Month", data: "Unlimited", ott: false, iptv: false },
  { id: 2, speed: "100 Mbps", price: 699, validity: "1 Month", data: "Unlimited", ott: false, iptv: false },
  { id: 3, speed: "150 Mbps", price: 799, validity: "1 Month", data: "Unlimited", ott: true, iptv: false },
  { id: 4, speed: "200 Mbps", price: 999, validity: "1 Month", data: "Unlimited", ott: true, iptv: true },
  { id: 5, speed: "300 Mbps", price: 1199, validity: "1 Month", data: "Unlimited", ott: true, iptv: true },
];

export const businessPlans = [
  { id: 1, speed: "100 Mbps", price: 1199, validity: "1 Month", data: "Unlimited", staticIp: true, gst: true },
  { id: 2, speed: "200 Mbps", price: 1999, validity: "1 Month", data: "Unlimited", staticIp: true, gst: true },
  { id: 3, speed: "300 Mbps", price: 4999, validity: "1 Month", data: "Unlimited", staticIp: true, gst: true },
  { id: 4, speed: "500 Mbps", price: 6999, validity: "1 Month", data: "Unlimited", staticIp: true, gst: true },
];

export const ottServices = [
  { name: "Aha Telugu", img: "https://veganet.in/assets/images/otts/ahatelugu.png" },
  { name: "Sun NXT", img: "https://veganet.in/assets/images/otts/sunnxt.png" },
  { name: "Zee5", img: "https://veganet.in/assets/images/otts/zee5.jpeg" },
  { name: "Sony LIV", img: "https://veganet.in/assets/images/otts/sonyliv.png" },
  { name: "Hotstar", img: "https://veganet.in/assets/images/otts/hotstar.png" },
  { name: "Prime Video", img: "https://veganet.in/assets/images/otts/primevideo.jpg" },
  { name: "Kanchalanka", img: "https://veganet.in/assets/images/otts/kanchalanka.jpg" },
  { name: "Runn TV", img: "https://veganet.in/assets/images/otts/runntv.png" },
  { name: "Channa Jor", img: "https://veganet.in/assets/images/otts/channajor.png" },
  { name: "Hubhopper", img: "https://veganet.in/assets/images/otts/hubhopper.png" },
  { name: "Om TV", img: "https://veganet.in/assets/images/otts/omtv.png" },
  { name: "Distro TV", img: "https://veganet.in/assets/images/otts/distrotv.png" },
  { name: "Power Kids", img: "https://veganet.in/assets/images/otts/powerkids.png" },
  { name: "iTap", img: "https://veganet.in/assets/images/otts/itap.png" },
  { name: "Playflix", img: "https://veganet.in/assets/images/otts/playflix.png" },
  { name: "Hungama Play", img: "https://veganet.in/assets/images/otts/hungamaplay.png" },
  { name: "Hoichoi", img: "https://veganet.in/assets/images/otts/hoichoi.png" },
  { name: "Fancode", img: "https://veganet.in/assets/images/otts/fancode.png" },
  { name: "Cinema World", img: "https://veganet.in/assets/images/otts/cinemaworld.png" },
  { name: "Alt Balaji", img: "https://veganet.in/assets/images/otts/altbalaji.png" },
  { name: "Namma Flix", img: "https://veganet.in/assets/images/otts/nammaflix.png" },
  { name: "ETV Win", img: "https://veganet.in/assets/images/otts/etvwin.jpeg" },
  { name: "Jio Cinema", img: "https://veganet.in/assets/images/otts/jiocinema.png" },
  { name: "Aha Tamil", img: "https://veganet.in/assets/images/otts/ahatamil.png" },
];

export const subscribeImage =
  "https://images.unsplash.com/photo-1601944179066-29786cb9d32a?w=1200&q=80";

export const iptvChannels = [
  "Star Plus", "Zee TV", "Sony TV", "Colors", "Star Sports 1", "Star Sports 2",
  "Sony Six", "Sony ESPN", "Discovery", "National Geographic", "Animal Planet",
  "History TV18", "Cartoon Network", "Pogo", "Nick", "Disney", "NDTV 24x7",
  "India Today", "CNN News18", "Times Now", "Aaj Tak", "Republic TV",
  "Zee News", "ABP News", "Star Gold", "Sony Max", "Zee Cinema", "& Pictures",
];

export const testimonials = [
  {
    name: "Ramesh Kumar",
    role: "Home User, Bangalore",
    quote: "VK Digital's fiber has been rock-solid for my work-from-home setup. Consistent speeds and quick support.",
  },
  {
    name: "Priya Sharma",
    role: "Small Business Owner",
    quote: "We upgraded to the business plan with static IP and GST billing. Best decision we made this year.",
  },
  {
    name: "Arjun Reddy",
    role: "Gamer & Streamer",
    quote: "Low latency, zero buffering on 4K streams. The OTT combo saves me so much money each month.",
  },
];
